### ISSUE TITLE
这个项目流产了。。。

### ISSUE THREAD

**Issue by pennpeng** [open-falcon/of-release#12]
两年木有更新了？？？

**Comment by laiwei** [comment]
参考 

https://github.com/open-falcon/falcon-plus 
https://github.com/open-falcon/dashboard

**Comment by softyun1** [comment]
falcon-plus什么时候出release版本，开发中的版本不敢用啊

**Comment by lijwww** [comment]
记得 群里贴出过360的版本,和美团的版本看起来都挺好的, 但是没有开源

**Comment by laiwei** [comment]
@softyun1 4月下旬可以发布
@lijwww 恩，会有一些通用的功能点开源的
