### ISSUE TITLE
使用 open-falcon ，发现如果被监控端宕机，不能触发告警

### ISSUE THREAD

**Issue by membphis** [open-falcon/of-release#6]
模板配置：

| metric | /tags/note | condition | max | P | run |
| --- | --- | --- | --- | --- | --- |
| agent.alive | [机器宕机] | all(#3)!=1 | 3 | 1 | run |

问下被监控端的宕机，如何处理

**Comment by laiwei** [comment]
agent down掉后，就没有办法上报数据了，所以这个告警永远不会触发

你需要参考一下nodata这个模块

**Comment by walnut-tom** [comment]
那 agent.alive 这个 metric 还有意义吗？是不是就不用上报了。agent down掉后 nodata 直接模拟一个是不是就可以了？

**Comment by zzlyzq** [comment]
nodata官方的解释是 一些重要的参数若干时间内没有上报就会模拟一个数据进行上报。
不过nodata也是可以用于机器宕机的报警的啦，不过貌似不能一次添加多个endpoint，分组倒是可以。

**Comment by lianfulei** [comment]
用nodata
