### ISSUE TITLE
hbase需要额外部署么

### ISSUE THREAD

**Issue by metchick** [open-falcon/of-release#7]
falcon的graph组件 我要部署多个的话 需要部署hbase么

**Comment by metchick** [comment]
还是说graph带的rrd就已经可以达到分布式存储的功能？

**Comment by laiwei** [comment]
不需要部署hbase，OpenFalcon数据都是存储在graph中，graph本身就是可扩展的：）

**Comment by metchick** [comment]
那就是说每个graph对应的rrd目录 内容是一样的？
